### PR TITLE
More types

### PR DESCRIPTION
**Pull request by ghost**
- Added some more types
- Reorganized the examples
- Changed the description to "ProtoDef implementation using protodefc and protodefc-prebuilt" -
- Moved errors to it's own file

<details>
<summary>This pull request adds the following types (click the dropdown)</summary>

- [x] f32
- [x] f64
- [x] li16
- [x] lu16
- [x] li32
- [x] lu32
- [x] lf32
- [x] lf64
- [x] li64
- [x] lu64
- [x] varint
- [x] bool
- [x] void
- [ ] pstring
- [ ] buffer
- [ ] cstring 

</details>
<br/>
I also separated the types into their respective files (this requires the types to be loaded because the object spread operator doesn't exist yet...)
<details>
<summary>Is this slow? Should I just move all the types into one file? (click to see code)</summary>

```js
let numeric = require('./types/numeric');
let utils = require('./types/utils');

// Copy numeric to root namespace
Object.keys(numeric).forEach(function(key) {
  module.exports['::' + key] = numeric[key];
});

// Copy utils to root namespace
Object.keys(utils).forEach(function(key) {
  module.exports['::' + key] = utils[key];
});
```
</details>

### CODE REVIEW

**Comment by rom1504** [comment]
dropdowns, fun

**Comment by rom1504** [comment]
partial read error https://github.com/ProtoDef-io/node-protodef/blob/master/src/datatypes/numeric.js#L67

**Comment by rom1504** [comment]
other than that, it looks ok

**Comment by rom1504** [comment]
can i merge ?

**Comment by ghost** [comment]
You can merge if you like, sure. Unless you want me to make those changes first. I don't have time right this second though.

**Comment by rom1504** [comment]
No it's fine the changes can be done afterwards

**Pull request merged**
